# Generated by Django 3.2.4 on 2021-06-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pizza/images')),
                ('type', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=225, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('Not available', 'Not available')], max_length=100, null=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizza')),
            ],
        ),
    ]
